name: Publish Org Config

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export Org Files
        uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          export: html
          files: config.org
          force_orphan: true
